name: BlazeDemo-Selenium-Cucumber-CI

on:
  push:
    branches:
      - test-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run tests and generate Masterthought Cucumber Report
        run: mvn clean verify

      - name: Upload Masterthought Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: masterthought-cucumber-report
          path: target/cucumber-reports
